---
- name: Build on Mac OS
  hosts: macos
  tasks:
      - include_tasks: macos/tasks.yml
        when: macos
- name: Building on Windows
  hosts: windows
  vars:
    - win_work_dir: C:\build\src\roschat
  tasks:
      - include_tasks: windows/tasks.yml
        when: windows
# - name: Build on *.deb
#   hosts: deb
#   tasks:
#       - include_tasks: linux/deb/tasks.yml
#         when: deb
# - name: Build on *.rpm
#   hosts: rpm
#   tasks:
#       - include_tasks: linux/rpm/tasks.yml
#         when: rpm
