---

- name: Prepare build servers
  hosts: setup
  # become: True
  tasks:
    - name: Install packages
      win_chocolatey:
          name: '{{ item }}'
          state: present
      with_items:
          - git
          - nodejs
          - innosetup
          - psexec
