---
- app:
        git:
            branch: electron
            url: &giturl ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/web_server
            tag: 0.0.0
        name: roschat-client
        productName: РосЧат
        type: client
        buildCmd: cd clients/demo && python3 build.py ${VERSION} ${BUILD_NUMBER} *giturl
        buildMachine: debian
        platforms:
            deb: true
            macos: true
            rpm: true
            windows: true
- app:
        git:
            branch: master
            url: ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/web_server
            tag: 0.0.0
        name: roschat-server
        productName: roschat-server
        type: server
        buildCmd: make all prj_version=${VERSION} prj_build=${BUILD_NUMBER}
        buildMachine: centos
        platforms:
            deb: false
            macos: false
            rpm: true
            windows: false
- app:
        git:
            branch: master
            url: ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/db_server
            tag: 0.0.0
        name: roschat-db
        productName: roschat-db
        type: server
        buildCmd: make build prj_version=${VERSION} prj_build=${BUILD_NUMBER}
        buildMachine: centos
        platforms:
            deb: false
            macos: false
            rpm: true
            windows: false
- app:
        git:
            branch: master
            url: ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/sip_server
            tag: 0.0.0
        name: roschat-sip
        productName: roschat-sip
        type: server
        buildCmd: make build prj_version=${VERSION} prj_build=${BUILD_NUMBER}
        buildMachine: centos
        platforms:
            deb: false
            macos: false
            rpm: true
            windows: false
- app:
        git:
            branch: master
            url: ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/managment-system-server
            tag: 0.0.0
        name: roschat-ms
        productName: roschat-ms
        type: server
        buildCmd: rpmbuild -bb -D "prj_version ${VERSION}" -D "prj_build ${BUILD_NUMBER}" -D "src_dir ${WORKSPACE}" roschat-ms.spec
        buildMachine: centos
        platforms:
            deb: false
            macos: false
            rpm: true
            windows: false
