---
- app:
        git:
            branch: electron
            url: ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/web_server
            tag: 0.0.0
        name: roschat-client
        productName: РосЧат
        type: desktop
        buildCmd: ./build.py RosChat prj_version=${VERSION} prj_build=${BUILD_NUMBER}
        platforms:
            deb: true
            macos: true
            rpm: true
            windows: true
- app:
        git:
            branch: master
            url: ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/web_server
            tag: 0.0.0
        name: roschat-server
        productName: roschat-server
        type: server
        buildCmd: make all prj_version=${VERSION} prj_build=${BUILD_NUMBER}
        platforms:
            deb: false
            macos: false
            rpm: true
            windows: false
- app:
        git:
            branch: master
            url: ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/db_server
            tag: 0.0.0
        name: roschat-db
        productName: roschat-db
        type: server
        buildCmd: make build prj_version=${VERSION} prj_build=${BUILD_NUMBER}
        platforms:
            deb: false
            macos: false
            rpm: true
            windows: false
- app:
        git:
            branch: master
            url: ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/web_server
            tag: 0.0.0
        name: sip-server
        productName: sip-server
        type: server
        buildCmd: make build prj_version=${VERSION} prj_build=${BUILD_NUMBER}
        platforms:
            deb: false
            macos: false
            rpm: true
            windows: false
- app:
        git:
            branch: master
            url: ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/managment-system-server
            tag: 0.0.0
        name: sma-server
        productName: sma-server
        type: server
        # buildCmd: rpmbuild -bb -D \"prj_version ${VERSION}\" -D \"prj_build ${BUILD_NUMBER}\" -D \"src_dir ${WORKSPACE}\" rms.spec
        buildCmd: rpmbuild -bb -D prj_version=${VERSION} -D prj_build=${BUILD_NUMBER} -D src_dir=${WORKSPACE} rms.spec
        platforms:
            deb: false
            macos: false
            rpm: true
            windows: false
- app:
        git:
            branch: master
            url: ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/web_server
            tag: 0.0.0
        name: build-test
        productName: build-test
        type: server
        buildCmd: echo prj_version=${VERSION} prj_build=${BUILD_NUMBER}
        platforms:
            deb: false
            macos: false
            rpm: false
            windows: false
