app:
  build: 190
  git:
    branch: electron
    url: git clone ssh://shavlovskiy_sn:123456@10.10.199.35/opt/git/firelink/web_server
  name: РосЧат
  platforms:
    deb: false
    macos: true
    rpm: true
    windows: false
  version: 0.0.286
